version: "3.8"
# Jupyter Notebook service for convenience
services:
  jupyter_notebook:
    image: jupyter/minimal-notebook
    container_name: jupyter_notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - 8888:8888
    volumes:
      - /home/jsida/namesApp:/home/jovyan/work
    depends_on:
      - database
    links:
      - database
    networks:
      - etl_network

  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: names
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-d",
          "names"
        ]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - /tmp/pg-data/:/var/lib/postgresql/data/
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_network

  dataviz:
    image: metabase/metabase:latest
    container_name: "metabase"
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: names
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: database
      MB_DB_FILE: /metabase-data/names.db
    depends_on:
    - database
    volumes:
      - dataviz_data:/metabase-data
    ports:
      - 3000:3000
    networks:
      - etl_network

volumes:
  dbdata: null
  dataviz_data: null

# Create a custom network for bridging the containers
networks:
  etl_network: null
